name: 🐛 Bug Report
description: Submit a bug report to help improve SyntaxUI

title: '[BUG]: '

labels: [Bug]
body:
  - type: markdown
    attributes:
      value: |
        Fill in the information below to help us understand and resolve the problem quickly.

        Instructions:
          1. Provide a clear and concise description of the bug.
          3. Include screenshots if applicable.

        Thank you for helping us improve SyntaxUI! 🙌
  - type: textarea
    attributes:
      label: Description 📝
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: input
    attributes:
      label: Link 🔗
      description: Link to the page where the bug occurred.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots 📸
      description: If applicable, add screenshots to help explain the problem.
    validations:
      required: true
