name: ✨ Feature Request
description: Suggest a new Feature or Component to enhance SyntaxUI

title: '[FEATURE]: '

labels: [Enhancement]
body:
  - type: markdown
    attributes:
      value: |
        Fill in the information below to help us understand and evaluate your feature or component request.
  - type: textarea
    attributes:
      label: Feature/Component Description 📝
      description: A clear and concise description of the new feature or component.
    validations:
      required: true
   - type: textarea
    attributes:
      label: Screenshot 📸
      description: Add a screenshot of the feature or component you are requesting.
    validations:
      required: false
